// Every user-facing string lives here. Have the owner read these aloud before you
// ship — wage vocabulary is regional.

export const ur = {
  app: {
    name: 'روزنامچہ',
    tagline: 'حاضری اور حساب',
    localMode: 'آف لائن ٹیسٹ موڈ — ڈیٹا صرف اس فون پر ہے',
  },
  nav: {
    home: 'ہوم',
    projects: 'پراجیکٹ',
    workers: 'مزدور',
    directory: 'تمام مزدور',
    attendance: 'حاضری',
    settings: 'ترتیبات',
  },
  auth: {
    title: 'لاگ اِن',
    email: 'ای میل',
    password: 'پاس ورڈ',
    signIn: 'داخل ہوں',
    signOut: 'لاگ آؤٹ',
    failed: 'ای میل یا پاس ورڈ درست نہیں',
    noMembership: 'یہ اکاؤنٹ کسی کمپنی سے منسلک نہیں۔ مالک سے رابطہ کریں۔',
    signOutConfirm: 'لاگ آؤٹ کرنے سے اس فون کا ڈیٹا صاف ہو جائے گا۔ جو اندراج ابھی اپ لوڈ نہیں ہوئے وہ ضائع ہو جائیں گے۔',
  },
  role: {
    owner: 'مالک',
    munshi: 'منشی',
  },
  project: {
    title: 'پراجیکٹ',
    code: 'پراجیکٹ نمبر',
    name: 'نام',
    address: 'پتہ',
    new: 'نیا پراجیکٹ',
    edit: 'پراجیکٹ میں تبدیلی',
    archive: 'بند کریں',
    unarchive: 'دوبارہ کھولیں',
    archived: 'بند پراجیکٹ',
    showArchived: 'بند پراجیکٹ دکھائیں',
    hideArchived: 'بند پراجیکٹ چھپائیں',
    workerCount: 'مزدور',
    empty: 'ابھی کوئی پراجیکٹ نہیں۔ نیچے سے نیا پراجیکٹ بنائیں۔',
    pick: 'پراجیکٹ منتخب کریں',
    codeRequired: 'پراجیکٹ نمبر اور نام ضروری ہیں',
    codeTaken: 'یہ پراجیکٹ نمبر پہلے سے موجود ہے',
  },
  dashboard: {
    todayAttendance: 'آج کی حاضری',
    giveAdvance: 'پیشگی دیں',
    giveEntry: 'رقم کا اندراج',
    markAttendance: 'حاضری لگائیں',
    workersOnProject: 'اس پراجیکٹ کے مزدور',
    notSaved: 'محفوظ نہیں ہوئے',
    notSavedHelp: 'یہ اندراج سرور نے قبول نہیں کیے۔ مالک سے بات کریں اور دوبارہ درج کریں۔',
    dismiss: 'ہٹا دیں',
  },
  worker: {
    name: 'نام',
    fatherName: 'والد کا نام',
    phone: 'موبائل نمبر',
    cnicLast4: 'شناختی کارڈ کے آخری 4 ہندسے',
    rate: 'دیہاڑی',
    trade: 'کام',
    new: 'نیا مزدور',
    edit: 'مزدور کی تفصیل',
    search: 'نام یا موبائل نمبر سے تلاش کریں',
    notFound: 'کوئی مزدور نہیں ملا',
    createNew: 'نیا مزدور بنائیں',
    nameRequired: 'نام ضروری ہے',
    duplicatePhone: 'اسی موبائل نمبر کا مزدور پہلے سے موجود ہے:',
    duplicateName: 'اسی نام اور والد کے نام کا مزدور پہلے سے موجود ہے:',
    duplicateQuestion: 'کیا یہ وہی شخص ہے؟',
    useExisting: 'ہاں، وہی ہے',
    createAnyway: 'نہیں، نیا بنائیں',
    onProjects: 'پراجیکٹ:',
    noProjects: 'کسی پراجیکٹ پر نہیں',
    inactive: 'غیر فعال',
    son: 'ولد',
  },
  trade: {
    mason: 'مستری',
    labourer: 'مزدور',
    carpenter: 'بڑھئی',
    steelFixer: 'سریا والا',
    electrician: 'الیکٹریشن',
    plumber: 'پلمبر',
    painter: 'رنگ ساز',
  },
  assignment: {
    title: 'پراجیکٹ پر لگائیں',
    rate: 'دیہاڑی (روپے)',
    startedOn: 'شروع',
    save: 'پراجیکٹ پر لگائیں',
    alreadyOn: 'یہ مزدور پہلے سے اس پراجیکٹ پر ہے',
    rateRequired: 'دیہاڑی درج کریں',
    ownerOnly: 'دیہاڑی صرف مالک طے کر سکتا ہے۔ مالک سے کہیں کہ اس مزدور کو پراجیکٹ پر لگائے۔',
    perDay: 'روزانہ',
    end: 'پراجیکٹ سے ہٹائیں',
    endConfirm: 'اس مزدور کو اس پراجیکٹ سے ہٹا دیں؟ اس کا کھاتہ محفوظ رہے گا۔',
    ended: 'پراجیکٹ سے ہٹ چکا',
    changeRate: 'دیہاڑی بدلیں',
    changeRateHelp: 'نئی دیہاڑی صرف آج کے بعد کی حاضری پر لگے گی۔ پرانا حساب نہیں بدلے گا۔',
  },
  attendance: {
    title: 'حاضری',
    full: 'پورا دن',
    half: 'آدھا دن',
    absent: 'غیر حاضر',
    tapHelp: 'سب حاضر لگے ہیں۔ آدھے دن یا غیر حاضر کے لیے نام پر ٹیپ کریں۔',
    save: 'حاضری محفوظ کریں',
    saved: 'حاضری محفوظ ہو گئی',
    notSavedYet: 'ابھی محفوظ نہیں',
    noWorkers: 'اس دن اس پراجیکٹ پر کوئی مزدور نہیں تھا',
    dayWages: 'اس دن کی دیہاڑی',
    marked: 'لگ چکی',
    of: 'میں سے',
    notMarked: 'ابھی نہیں لگی',
    complete: 'پوری لگی',
    partial: 'کچھ باقی',
    missing: 'نہیں لگی',
    prevMonth: 'پچھلا مہینہ',
    nextMonth: 'اگلا مہینہ',
    futureDay: 'آنے والے دن کی حاضری نہیں لگ سکتی',
    lockedOld: '7 دن سے پرانی حاضری صرف مالک بدل سکتا ہے',
    days: 'دن',
  },
  entry: {
    advance: 'پیشگی',
    payment: 'ادائیگی',
    deduction: 'کٹوتی',
    bonus: 'انعام',
    correction: 'تصحیح',
    new: 'رقم کا اندراج',
    kind: 'قسم',
    amount: 'رقم (روپے)',
    note: 'نوٹ (اختیاری)',
    date: 'تاریخ',
    worker: 'مزدور',
    pickWorker: 'مزدور منتخب کریں',
    amountRequired: 'درست رقم درج کریں',
    workerRequired: 'مزدور منتخب کریں',
    backdateTitle: 'پرانی تاریخ',
    backdateBody: 'یہ اندراج 7 دن سے زیادہ پرانا ہے۔ کیا آپ کو یقین ہے؟',
    futureDate: 'آنے والی تاریخ کا اندراج نہیں ہو سکتا',
    confirmTitle: 'تصدیق کریں',
    reverse: 'تصحیح کریں',
    reverseConfirm: 'یہ اندراج منسوخ کرنے کے لیے تصحیح کا اندراج بنے گا۔ اصل اندراج کھاتے میں رہے گا۔',
    reversed: 'منسوخ شدہ',
    reverses: 'منسوخی:',
    receiptSent: 'پرچی بھیجی گئی',
    receiptPending: 'پرچی نہیں بھیجی',
  },
  ledger: {
    title: 'کھاتہ',
    empty: 'ابھی کوئی اندراج نہیں',
    earned: 'کمائی',
    grandTotal: 'تمام پراجیکٹ کا کل',
    grandTotalHelp: 'ہر پراجیکٹ کا حساب الگ ہے۔ یہ صرف مجموعہ ہے۔',
  },
  balance: {
    owedToWorker: 'ہمارے ذمے',
    owedByWorker: 'وصول طلب',
    settled: 'حساب برابر',
    total: 'کل بقایا',
    newBalance: 'نیا بقایا',
  },
  receipt: {
    title: 'پرچی',
    send: 'پرچی بھیجیں',
    sendText: 'واٹس ایپ پیغام بھیجیں',
    reason: 'وجہ',
    ref: 'حوالہ نمبر',
    project: 'پراجیکٹ',
    sendNow: 'رقم دینے سے پہلے، مزدور کے سامنے پرچی بھیجیں',
    sent: 'پرچی بھیج دی گئی',
    shareUnavailable: 'اس فون پر شیئر کرنا ممکن نہیں',
    noPhone: 'اس مزدور کا موبائل نمبر درج نہیں',
    done: 'مکمل',
  },
  sync: {
    synced: 'سب محفوظ',
    pending: 'اپ لوڈ باقی',
    offline: 'آف لائن',
    connecting: 'رابطہ ہو رہا ہے',
    firstSync: 'ڈیٹا ڈاؤن لوڈ ہو رہا ہے…',
  },
  settings: {
    title: 'ترتیبات',
    account: 'اکاؤنٹ',
    business: 'کمپنی',
    version: 'ورژن',
    sync: 'سنک',
    updateReady: 'نیا ورژن تیار ہے',
    restart: 'ری اسٹارٹ کریں',
    language: 'زبان',
    languageHelp: 'زبان بدلنے پر ایپ دوبارہ کھلے گی۔ مزدور کو پرچی ہمیشہ اردو میں جائے گی۔',
  },
  update: {
    required: 'نیا ورژن ضروری ہے',
    requiredBody: 'یہ ورژن پرانا ہو چکا ہے۔ نیچے دیے گئے بٹن سے نیا ورژن ڈاؤن لوڈ کر کے انسٹال کریں۔',
    download: 'ڈاؤن لوڈ کریں',
  },
  date: {
    today: 'آج',
    yesterday: 'کل',
  },
  action: {
    save: 'محفوظ کریں',
    send: 'بھیجیں',
    share: 'شیئر کریں',
    cancel: 'منسوخ',
    confirm: 'ہاں',
    edit: 'تبدیل کریں',
    addWorker: 'نیا مزدور',
    back: 'واپس',
  },
  common: {
    rupees: 'روپے',
    error: 'مسئلہ',
    optional: 'اختیاری',
  },
} as const;
