// English strings. Same shape as strings.ur.ts — TypeScript fails the build if a key is
// missing here, so a new Urdu string can't ship without its English counterpart.
import type { ur } from './strings.ur';

type Widen<T> = { [K in keyof T]: T[K] extends string ? string : Widen<T[K]> };
export type Strings = Widen<typeof ur>;

export const en: Strings = {
  app: {
    name: 'Roznamcha',
    tagline: 'Attendance and accounts',
    localMode: 'Offline test mode — data stays on this phone only',
  },
  nav: {
    home: 'Home',
    projects: 'Projects',
    workers: 'Workers',
    directory: 'All workers',
    attendance: 'Attendance',
    settings: 'Settings',
  },
  auth: {
    title: 'Sign in',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    failed: 'Wrong email or password',
    noMembership: 'This account is not linked to a business. Ask the owner.',
    signOutConfirm: 'Signing out clears this phone’s data. Entries not yet uploaded will be lost.',
  },
  role: {
    owner: 'Owner',
    munshi: 'Munshi',
  },
  project: {
    title: 'Project',
    code: 'Project number',
    name: 'Name',
    address: 'Address',
    new: 'New project',
    edit: 'Edit project',
    archive: 'Close project',
    unarchive: 'Reopen project',
    archived: 'Closed project',
    showArchived: 'Show closed projects',
    hideArchived: 'Hide closed projects',
    workerCount: 'workers',
    empty: 'No projects yet. Create one below.',
    pick: 'Choose a project',
    codeRequired: 'Project number and name are required',
    codeTaken: 'This project number already exists',
  },
  dashboard: {
    todayAttendance: 'Today’s attendance',
    comingSoon: 'coming soon',
    giveAdvance: 'Give advance',
    giveEntry: 'Record money',
    markAttendance: 'Mark attendance',
    workersOnProject: 'Workers on this project',
    notSaved: 'Not saved',
    notSavedHelp: 'The server did not accept these entries. Talk to the owner and enter them again.',
    dismiss: 'Dismiss',
  },
  worker: {
    name: 'Name',
    fatherName: 'Father’s name',
    phone: 'Mobile number',
    cnicLast4: 'Last 4 digits of CNIC',
    rate: 'Daily wage',
    trade: 'Trade',
    new: 'New worker',
    edit: 'Worker details',
    search: 'Search by name or mobile number',
    notFound: 'No workers found',
    createNew: 'Create new worker',
    nameRequired: 'Name is required',
    duplicatePhone: 'A worker with this mobile number already exists:',
    duplicateName: 'A worker with this name and father’s name already exists:',
    duplicateQuestion: 'Is this the same person?',
    useExisting: 'Yes, same person',
    createAnyway: 'No, create new',
    onProjects: 'Projects:',
    noProjects: 'Not on any project',
    inactive: 'Inactive',
    son: 's/o',
  },
  trade: {
    mason: 'Mason',
    labourer: 'Labourer',
    carpenter: 'Carpenter',
    steelFixer: 'Steel fixer',
    electrician: 'Electrician',
    plumber: 'Plumber',
    painter: 'Painter',
  },
  assignment: {
    title: 'Add to project',
    rate: 'Daily wage (rupees)',
    startedOn: 'Started',
    save: 'Add to project',
    alreadyOn: 'This worker is already on this project',
    rateRequired: 'Enter the daily wage',
    ownerOnly: 'Only the owner can set wages. Ask the owner to add this worker to the project.',
    perDay: 'per day',
    end: 'Remove from project',
    endConfirm: 'Remove this worker from the project? Their ledger is kept.',
    ended: 'Removed from project',
    changeRate: 'Change daily wage',
    changeRateHelp: 'The new wage applies to attendance from today. Past accounts do not change.',
  },
  entry: {
    advance: 'Advance',
    payment: 'Payment',
    deduction: 'Deduction',
    bonus: 'Bonus',
    correction: 'Correction',
    new: 'Record money',
    kind: 'Type',
    amount: 'Amount (rupees)',
    note: 'Note (optional)',
    date: 'Date',
    worker: 'Worker',
    pickWorker: 'Choose a worker',
    amountRequired: 'Enter a valid amount',
    workerRequired: 'Choose a worker',
    backdateTitle: 'Old date',
    backdateBody: 'This entry is more than 7 days old. Are you sure?',
    futureDate: 'Entries can’t be dated in the future',
    confirmTitle: 'Confirm',
    reverse: 'Correct',
    reverseConfirm: 'This creates a correction that cancels the entry. The original stays in the ledger.',
    reversed: 'Cancelled',
    reverses: 'Cancels:',
    receiptSent: 'Receipt sent',
    receiptPending: 'Receipt not sent',
  },
  ledger: {
    title: 'Ledger',
    empty: 'No entries yet',
    earned: 'Earned',
    grandTotal: 'Total across all projects',
    grandTotalHelp: 'Each project is accounted separately. This is only the sum.',
  },
  balance: {
    owedToWorker: 'We owe',
    owedByWorker: 'Recoverable',
    settled: 'Settled',
    total: 'Total outstanding',
    newBalance: 'New balance',
  },
  receipt: {
    title: 'Receipt',
    send: 'Send receipt',
    sendText: 'Send WhatsApp message',
    reason: 'Reason',
    ref: 'Reference',
    project: 'Project',
    sendNow: 'Send the receipt in front of the worker, before handing over the cash',
    sent: 'Receipt sent',
    shareUnavailable: 'Sharing is not available on this phone',
    noPhone: 'This worker has no mobile number',
    done: 'Done',
  },
  sync: {
    synced: 'All saved',
    pending: 'to upload',
    offline: 'Offline',
    connecting: 'Connecting',
    firstSync: 'Downloading data…',
  },
  settings: {
    title: 'Settings',
    account: 'Account',
    business: 'Business',
    version: 'Version',
    sync: 'Sync',
    updateReady: 'A new version is ready',
    restart: 'Restart',
    language: 'Language',
    languageHelp: 'The app restarts when you change language. Workers always get the receipt in Urdu.',
  },
  update: {
    required: 'Update required',
    requiredBody: 'This version is too old. Download and install the new version with the button below.',
    download: 'Download',
  },
  date: {
    today: 'Today',
    yesterday: 'Yesterday',
  },
  action: {
    save: 'Save',
    send: 'Send',
    share: 'Share',
    cancel: 'Cancel',
    confirm: 'Yes',
    edit: 'Edit',
    addWorker: 'Add worker',
    back: 'Back',
  },
  common: {
    rupees: 'Rs',
    error: 'Problem',
    optional: 'optional',
  },
};
